### ISSUE TITLE
Compatibility with markdown-it@9.0.0?

### ISSUE THREAD

**Issue by CarlosJimenez** [arve0/markdown-it-attrs#90]
markdown-it-attrs@2.4.1 has dependency with markdown-it@8.4.2
Is compatible with markdown-it@9.0.0?

**Comment by arve0** [comment]
Have you tried?

```
git clone https://github.com/arve0/markdown-it-attrs
cd markdown-it-attrs
# bump version
npm i 
npm test 
```

**Comment by ahus1** [comment]
When I combine "markdown-it": "^9.0.1" with "markdown-it-attrs": "^2.3.2" I receive an error:

```
TypeError: Cannot read property 'attrPush' of undefined
    at Object.exports.addAttrs (C:\workspace\homepage\node_modules\markdown-it-attrs\utils.js:127:13)
    at Object.transform (C:\workspace\homepage\node_modules\markdown-it-attrs\patterns.js:131:15)
    at Array.curlyAttrs (C:\workspace\homepage\node_modules\markdown-it-attrs\index.js:30:19)
    at Core.process (C:\workspace\homepage\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (C:\workspace\homepage\node_modules\markdown-it\lib\index.js:523:13)
```

I assume they re now compatible (yet)?

**Comment by jimbojw** [comment]
I found a similar issue to @ahus1. Here's a simple example that demonstrates the problem:

```md
This is a paragraph of text with a *highlighted*{.hi} word in it.
```

In this example, I want the emphasized word "highlighted" to have the CSS class `hi` added to it.

The problem is in the `getMatchingOpeningToken()` method in `utils.js` starting here: https://github.com/arve0/markdown-it-attrs/blob/master/utils.js#L245

The current code treats block and inline elements differently. For inline elements like my `<em>` example here, the code adds 1 to the level of the token that it's looking for.

```js
  // inline tokens changes level on same token
  // that have .nesting +- 1
  let level = tokens[i].block
    ? tokens[i].level
    : tokens[i].level + 1;  // adjust for inline tokens
```

However, I've found that as of markdown-it version 9, the matching opening token for inline elements has the same level as the closing token.

Replacing the above code with the following fixes the issue:

```js
  let level = tokens[i].level;
```

**Comment by arve0** [comment]
Fixed in markdown-it-attrs v3.0.0

**Comment by ahus1** [comment]
I've upgraded to markdown-it 9.0.1 and markdown-it-attrs 3.0.0 and still get the exception, please re-open the issue.

Problematic code snippet: 

`[text](https://host/xxx){target="_blank" rel="noopener"}`

Exception:

```
Module build failed (from ./node_modules/@nuxtjs/markdownit-loader/index.js):                               friendly-errors 19:04:33
TypeError: Cannot read property 'attrPush' of undefined
    at Object.exports.addAttrs (C:\workspace\homepage\node_modules\markdown-it-attrs\utils.js:127:13)
    at Object.transform (C:\workspace\homepage\node_modules\markdown-it-attrs\patterns.js:131:15)
    at Array.curlyAttrs (C:\workspace\homepage\node_modules\markdown-it-attrs\index.js:30:19)
    at Core.process (C:\workspace\homepage\node_modules\@nuxtjs\markdownit-loader\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (C:\workspace\homepage\node_modules\@nuxtjs\markdownit-loader\node_modules\markdown-it\lib\index.js:523:13)
    at MarkdownIt.render (C:\workspace\homepage\node_modules\@nuxtjs\markdownit-loader\node_modules\markdown-it\lib\index.js:543:36)
    at Object.module.exports (C:\workspace\homepage\node_modules\@nuxtjs\markdownit-loader\lib\core.js:94:24)
```

**Comment by arve0** [comment]
Unable to reproduce: https://runkit.com/embed/v8v7my2g4d6w

Same in terminal:

```sh
$ cd /tmp
/tmp $ mkdir asdf
/tmp $ cd asdf
/t/asdf $ npm init -y
Wrote to /private/tmp/asdf/package.json:

{
  "name": "asdf",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


/t/asdf $ npm i markdown-it markdown-it-attrs
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN asdf@1.0.0 No description
npm WARN asdf@1.0.0 No repository field.

+ markdown-it@9.0.1
+ markdown-it-attrs@3.0.0
added 8 packages from 5 contributors and audited 9 packages in 2.446s
found 0 vulnerabilities

/t/asdf $ echo "let md = require('markdown-it')();
          let markdownItAttrs = require('markdown-it-attrs');
          
          md.use(markdownItAttrs);
          
          let src = '*highlighted*{.hi} word';
          console.log(md.render(src));
          " >> asdf.js
/t/asdf $ node asdf.js 
<p><em class="hi">highlighted</em> word</p>
```

Please provide steps to reproduce errors. Make sure you have the correct versions of markdown-it and markdown-it-attrs installed. Check with `npm ls`:

```sh
/t/asdf $ npm ls
asdf@1.0.0 /private/tmp/asdf
├─┬ markdown-it@9.0.1
│ ├─┬ argparse@1.0.10
│ │ └── sprintf-js@1.0.3
│ ├── entities@1.1.2
│ ├─┬ linkify-it@2.2.0
│ │ └── uc.micro@1.0.6 deduped
│ ├── mdurl@1.0.1
│ └── uc.micro@1.0.6
└── markdown-it-attrs@3.0.0
```

**Comment by ahus1** [comment]
Sorry, my fault. I was fooled by a transitive dependency that included mixed versions of markdown-it. Keep it closed.
