### ISSUE TITLE
Error is thrown with inline element

### ISSUE THREAD

**Issue by roobottom** [arve0/markdown-it-attrs#98]
I'm getting the following error

```
> Having trouble rendering liquid (and markdown) template ./_source/index.md
[0] 
[0] `TemplateContentRenderError` was thrown
[0] > Cannot read property 'attrJoin' of undefined
[0] 
[0] `TypeError` was thrown:
[0]     TypeError: Cannot read property 'attrJoin' of undefined
[0]         at Object.exports.addAttrs (/Users/roobottom/Git/roodesign-2019/node_modules/markdown-it-attrs/utils.js:123:13)
[0]         at Object.transform (/Users/roobottom/Git/roodesign-2019/node_modules/markdown-it-attrs/patterns.js:131:15)
[0]         at Array.curlyAttrs (/Users/roobottom/Git/roodesign-2019/node_modules/markdown-it-attrs/index.js:30:19)
[0]         at Core.process (/Users/roobottom/Git/roodesign-2019/node_modules/markdown-it/lib/parser_core.js:51:13)
[0]         at MarkdownIt.parse (/Users/roobottom/Git/roodesign-2019/node_modules/markdown-it/lib/index.js:523:13)
[0]         at MarkdownIt.render (/Users/roobottom/Git/roodesign-2019/node_modules/markdown-it/lib/index.js:543:36)
[0]         at /Users/roobottom/Git/roodesign-2019/node_modules/@11ty/eleventy/src/Engines/Markdown.js:72:38
[0]         at process._tickCallback (internal/process/next_tick.js:68:7)
```

When…

Example input:
```md
[Find out how I can help you](/services){.button} 
```

Current output:
```html
Nothing
```

Expected output:
```html
<p><a href="/services" class="button">Find out how I can help you</a></p>
```

Adding a space like this:

```md
[Find out how I can help you](/services) {.button} 
```

works, but applies the `button` class to `<p>` and not `<a>`

**Comment by arve0** [comment]
Unable to reproduce with latest versions: https://runkit.com/embed/4vjb2w5ibopx

**Comment by roobottom** [comment]
Markdown-it-attrs `3.0.1` and markdown whichever version ships with [11ty](https://www.11ty.io/) `0.9.0`

**Comment by arve0** [comment]
`npm ls markdown-it`

**Comment by roobottom** [comment]
`markdown-it@8.4.2`

**Comment by roobottom** [comment]
Ah, I can see that it's quite old. I'll upgrade to sort the problem.

**Comment by roobottom** [comment]
Thanks for your help!
